### ISSUE TITLE
Port the light theme

### ISSUE THREAD

**Issue by jsynowiec** [fcaldera/github-primer-iterm2#1]
Thanks for porting the dark theme. Can you also include the light variant?

**Comment by fedcho** [comment]
Hi @jsynowiec. Added the light variant, as closest to the integrated terminal in VS Code as I could.
How does it look?

**Comment by jsynowiec** [comment]
Thanks. I somehow missed your reply and did my own version: https://gist.github.com/jsynowiec/507f9c6f85288bf65d7d20abb3f99726
